#!/bin/bash

source initial-setup-audit.sh

#Audit Scripts

audit_cramfs_disabled
audit_squashfs_disabled
audit_udf_disabled
audit_tmp_partition_separate
audit_tmp_partition_nodev
audit_tmp_partition_noexec
audit_tmp_partition_nosuid
audit_var_partition_seperate
audit_var_partition_nodev
audit_tmp_partition_noexec
audit_var_partition_nosuid
audit_var_tmp_seperate_partition
audit_var_tmp_partition_noexec
audit_var_tmp_partition_nosuid
audit_var_tmp_partition_nodev
audit_var_log_partition_seperate
audit_var_log_partition_nodev
audit_var_log_partition_noexec
audit_var_log_partition_nosuid
audit_var_log_audit_seperate_partition
audit_var_log_audit_partition_noexec
audit_var_log_audit_partition_nodev
audit_var_log_audit_partition_nosuid
audit_home_sperate_partition
audit_home_partition_nodev
audit_home_partition_nosuid
audit_dev_shm_partition_nodev
audit_dev_shm_partition_noexec
audit_dev_shm_partition_nosui
audit_disable_automounting
audit_disable_usb_storage
audit_aide_installed
audit_file_sys_integrity_checked
audit_bootloader_pwd
audit_bootloader_config_permissions
audit_single_usr_auth
audit_aslr_enabled
audit_prelink_not_insalled
audit_automatic_err_reporting_disabled
audit_core_dumps_restricted
audit_apparmor_installed
audit_apparmor_enabled_bootloader
audit_apparmor_all_profiles_enforce_complian
audit_apparmor_all_profiles_enforcing
audit_message_ofthe_day_config
audit_banner_local_login_warning
audit_banner_remote_login_warning
audit_etc_motd_permissions_config
audit_etc_issue_permisions_config
audit_etc_issuenet_permisions_config
audit_gnome_display_mnger_rm
audit_gdm_login_banner_config
audit_gdm_disable_usr_list_enable
audit_gdm_screenlock_usr_idle
audit_gdm_screenlock_override
audit_gdm_auto_mounting_removable_disable
audit_gdm_auto_mounting_removable_disable_pr
audit_gdm_autorun_never_enable
audit_gmd_autorun_never_override
audit_xdcmp_notenabled
audit_updates_installed

